name: Generate SBOM in CycloneDX Format
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Download SBOM Tool
      run: curl -Lo sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
       chmod +x sbom-tool
    - name: Generate SBOM in CycloneDX Format
      run: ./sbom-tool generate -manifestDirPath ./ -b ~/.npm -bc . -pn npm -pv 1.0.0 -ps MyCompany -nsb https://sbom.mycompany.com -of cyclonedx -V Verbose
    - name: Upload SBOM
      uses: actions/upload-artifact@v3
      with:
        name: sbom-cyclonedx
        path: _manifest/cyclonedx/*
